extend type Card {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Card", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Card`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Card.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Expense {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Expense", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Expense`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Expense.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Goal {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Goal", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Goal`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Goal.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Household {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Household", purpose: IMPLICIT_KEY_FIELD)
}
extend type Income {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Income", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Income`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Income.user", purpose: IMPLICIT_REF_FIELD)
}
extend type MonthHistory {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "MonthHistory", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `MonthHistory`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "MonthHistory.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `User`.`household`. It must match the value of `Household`.`id`. See `@ref` for how to customize it.
  """
  householdId: UUID! @fdc_generated(from: "User.household", purpose: IMPLICIT_REF_FIELD)
}
